name: github-actions
run-name: melvin

on:
  push:
    branches:
      - feature

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        run: echo "Hello world"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Test
        run: 0-2.js